on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  main:
    name: Setup, build, and Deploy to gh-pages branch
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v4
      - name: Setting up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Installing and updating Bikeshed
        run: pip3 install bikeshed && bikeshed update
        shell: bash
      - name: Building index.html from index.bs
        run: bash ./compile.sh
        shell: bash
      - name: Deploying to gh-pages branch
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
